#!/usr/bin/bash
# Para mapeo en nvim:
# nnoremap <F8> :!./z % c<CR>
# nnoremap <F9> :!./z %<CR>
pric() {
  color=$1
  msj=$2

  case $color in
    r)
      echo -e "\e[31m$msj\e[0m"
      ;;
    g)
      echo -e "\e[32m$msj\e[0m"
      ;;
  esac
}


source_file=$1
options=$2

# Initialize variables
file=$(readlink -f "$source_file")
file_name="${file##*/}"
file_type="${file_name##*.}"
file_not_ext="${file_name%.*}"
file_directory="$( dirname $file )"

cpp_version="c++23"
input_file="in"


if [[ "$file_type" == "cpp" ]]; then
  if [[ "$options" == "c" ]]; then
    #pric r "Compilar"
    echo "######################"
    echo "###### COMPILAR ######"
    echo "######################"
    g++ "$file" -std="$cpp_version" -Wall -Wextra -Wshadow \
      -Wconversion -Wfatal-errors \
      -o "$file_not_ext" \
      && cat "$file_directory/$input_file" | ./"$file_not_ext"
  else 
    cat "$file_directory/$input_file" | ./$file_not_ext
  fi
elif [[ "$file_type" == "py" ]]; then
  cat "$file_directory/$input_file" | python3 "$file"
fi
